=== En-Query/EncryptedQuery/xml/src/main/resources/org/enquery/encryptedquery/xml/schema/data-schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
  EncryptedQuery is an open source project allowing user to query databases with queries under homomorphic encryption to securing the query and results set from database owner inspection. 
  Copyright (C) 2018  EnQuery LLC 
 
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.
 
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.
 
  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 -->
<xs:schema
	targetNamespace="http://enquery.net/encryptedquery/dataschema"
	xmlns="http://enquery.net/encryptedquery/dataschema"
	xmlns:ds="http://enquery.net/encryptedquery/dataschema"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xs:element name="dataSchema" type="dataSchema">
		<xs:unique name="uniqueFieldNames">
              <xs:selector xpath="ds:field"/>
              <xs:field xpath="ds:name"/>
        </xs:unique>
        <xs:unique name="uniqueFieldPositions">
			<xs:selector xpath="ds:field" />
			<xs:field xpath="ds:position" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="dataSchema">
		<xs:sequence>
			<xs:element name="name" type="xs:string">
				<xs:annotation>
					<xs:documentation>The name of the data
						schema. The name omits
						leading and trailing whitespace, and is case
						sensitive.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="field" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="xs:string">
							<xs:annotation>
								<xs:documentation>The name of the data
									element. The name omits
									leading and trailing whitespace, and is case
									sensitive.
								</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="dataType" type="xs:string">
							<xs:annotation>
								<xs:documentation>The type of the data
									element. The type name is
									the fully qualified class name, or the
									primitive
									Java type of the
									element.
								</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="position" type="xs:int" default="0">
							<xs:annotation>
								<xs:documentation> Index of this field in the data schema. This
									is used to
									be able to lookup fields by position instead of by
									name. In some
									data sources,
									like JDBC, or flat files (TBS, CSV,
									etc.) looking fields by name is
									not possible.
								</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== En-Query/EncryptedQuery/xml/src/test/resources/duplicate-field-position-dataschema.xml
<dataSchema xmlns="http://enquery.net/encryptedquery/dataschema" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://enquery.net/encryptedquery/dataschema 
		../../main/resources/org/enquery/encryptedquery/xml/schema/data-schema.xsd">
		
	<name>name</name>
	
	<field>
		<name>name1</name>
		<dataType>int</dataType>
		<isArray>false</isArray>
		<position>0</position>
	</field>
	
	<field>
		<name>name2</name>
		<dataType>int</dataType>
		<isArray>false</isArray>
		<!-- position duplicate -->
		<position>0</position>
	</field>
</dataSchema>
